jacom/urls.py
from django.contrib import admin
from django.urls import include, path
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users_accounts.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

users_accounts/urls.py
from django.urls import path
from .views import HomePage, CreateUser, UserProfileView, UpdateProfile, DeleteUser, LoginView, Logout, AboutPage, ContactPage, CreateProfile, TestimonialsPage, FaqPage, PrivacyPolicyPage, HowItWorksPage, Dashbord, search_view
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users_accounts'

urlpatterns = [
    path('', HomePage.as_view(), name = 'homepage'),
    path('user_signup', CreateUser.as_view(), name = 'signup'),
    path('user_login', LoginView.as_view(), name = 'login'),
    path('user_logout', Logout, name = 'logout'),
    path('user_profile', UserProfileView.as_view(), name = 'profile'),
    path('create_profile', CreateProfile.as_view(), name = 'userprofile'),
    path('user_update/<pk>', UpdateProfile.as_view(), name = 'update'),
    path('user_delete/<pk>', DeleteUser.as_view(), name = 'delete'),
    path('about_us', AboutPage.as_view(), name = 'about'),
    path('contact_us', ContactPage.as_view(), name = 'contact'),
    path('testimonials',TestimonialsPage.as_view(), name = 'testimony'),
    # path('terms/',TermsOfService.as_view(), name = 'terms&service'),
    path('terms/', views.terms_of_service, name='terms_of_service'),
    path('faq', FaqPage.as_view(), name = 'faqpage'),
    path('privacy_policy', PrivacyPolicyPage.as_view(), name = 'privacy&policy'),
    path('functionl', HowItWorksPage.as_view(), name = 'functioning'),
    path('dashboard_page', Dashbord.as_view(), name = 'dashboard'),
    path('search_page', search_view, name='search'),
    path('user/search/', views.user_search, name='user_search'),
    path('geolocation/', views.geolocation_view, name='geolocation'),
    path('job_count/', views.job_count, name='job_count'),
    path('account/status/', views.account_status, name='account_status'),
    path('withdrawal_requests/', views.withdrawal_requests_view, name='withdrawals'),
    path('ongoing_projects/',views.ongoing_projects_view, name='ongoing_project'),
    #password reset
    path('reset_password', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='reset_password'),
    path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),  name='password_reset_done'),
    path('reset/<uid64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
]

users_accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image as Im

# Create your models here.
class Customer(models.Model):
    CHOICES = (
        ('Employer', 'Employer'),
        ('user', 'user'),
    )
    category = models.CharField(max_length=20, choices=CHOICES, default='user')

    def __str__(self):
        return self.category

from django.db import models

class TermsOfService(models.Model):
    contents = models.TextField()
    date_updated = models.DateTimeField(auto_now=True)
    
class Earnings(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    # Other fields

class PendingPayments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    # Other fields

class WithdrawalRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField(auto_now_add=True)
    status = models.CharField(max_length=20, default='pending')
    is_approved = models.BooleanField(default=False)
    # Other fields


class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(unique=True)
    profile_pictures = models.ImageField(unique=True, default='img.png', upload_to='pics')
    work_bio = models.TextField(default='write a short bio about yourself')
    mobile_number = models.IntegerField(default="123...")
    dob = models.DateField()
    GENDER_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female')
    ]
    gender = models.CharField(max_length=200, choices=GENDER_CHOICES, default="Gender")
    category = models.ForeignKey(Customer, on_delete=models.CASCADE)
    content = models.TextField(default="search content")
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_verified = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    STATUS_CHOICES = [
        ('In Progress', 'In Progress'),
        ('Completed', 'Completed'),
        ('On Hold', 'On Hold'),
    ]
    client = models.CharField(max_length=100)
    deadline = models.DateField(default="Deadline")
    title = models.CharField(max_length=255, default="Job Title")
    status = models.CharField(max_length=200, choices=STATUS_CHOICES ,default="In Progress")

    def __str__(self):
        return self.first_name
        return self.title

    def save(self):
        super().save()
        img = Im.open(self.profile_pictures.path)

        if img.height > 90 or img.width > 90:
            output_size = (90, 90)
            img. thumbnail(output_size)
            img.save(self.profile_pictures.path)

users_accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import UserProfile, WithdrawalRequest
from django import forms

class CreateUserForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class LoginUserForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')

class ProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ('__all__')

class SearchForm(forms.Form):
    search_term = forms.CharField(max_length=255)

class AcceptTOSForm(forms.Form):
    accepted = forms.BooleanField(label='I accept the Terms of Service')

class WithdrawalRequestForm(forms.ModelForm):
    class Meta:
        model = WithdrawalRequest
        fields = ['amount']

users_accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.conf import settings

# Create your views here.
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, TemplateView, View

from .forms import CreateUserForm, LoginUserForm, ProfileForm, SearchForm
from django.http import JsonResponse
from .models import UserProfile
from .models import TermsOfService
from .models import Earnings, PendingPayments, WithdrawalRequest
from .forms import AcceptTOSForm, WithdrawalRequestForm
import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY

class HomePage(TemplateView):
    template_name = 'home.html'

class CreateUser(CreateView):
    template_name = 'sign_up.html'
    queryset = User.objects.all()
    form_class = CreateUserForm

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            username = request.POST.get('username')
            email = request.POST.get('email')
            password = request.POST.get('password')

            user = User.objects.create_user(username, email, password)
            user.save()
            return redirect('/user_login')
        else:
            return render('Invalid Signup')

def Logout(request):
    logout(request)
    return redirect('/user_login')

class LoginView(CreateView):
    template_name = 'login.html'
    queryset = User.objects.all()
    form_class = LoginUserForm

    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/dashboard_page')
        else:
            return render({'details':'Not Found'}, self.template_name)

class CreateProfile(LoginRequiredMixin, CreateView):
    template_name = 'create_profile.html'
    queryset = UserProfile.objects.all
    form_class = ProfileForm
    success_url = '/user_profile'
    login_url = '/user_login'
    

class UserProfileView(LoginRequiredMixin, ListView):
    template_name = 'user_profile.html'
    queryset = UserProfile.objects.all()
    context_object_name = 'user'
    login_url = '/user_login'

    # def get(request):
    #     user_data = UserProfile.objects.filter(user=request.user)
    #     return render(request, self.template_name, {'user':user_data})

class UpdateProfile(LoginRequiredMixin, UpdateView):
    template_name = 'update.html'
    queryset = UserProfile.objects.all()
    form_class = ProfileForm
    success_url = '/user_profile'
    login_url = '/user_login'

class DeleteUser(LoginRequiredMixin, DeleteView):
    template_name = 'delete.html'
    queryset = UserProfile.objects.all()
    context_object_name = 'delete'
    success_url = '/user_profile'
    login_url = '/user_login'

def search_view(request):
    query = request.GET.get('q')

    if query:
        results = UserProfile.objects.filter(title__icontains=query)
        # Adjust 'your_field' to the field you want to search on

        return render(request, 'search_results.html', {'results': results})
    else:
        return render(request, 'search_results.html', {'results': []})

def user_search(request):
    if 'search_query' in request.GET:
        search_query = request.GET['search_query']
        users = userprofile.objects.filter(title__icontains=search_query)
        return render(request, 'user_search.html', {'users': users})
    else:
        return render(request, 'user_search.html', {})



def geolocation_view(request):
    if request.method == 'POST':
        latitude = request.POST.get('latitude')
        longitude = request.POST.get('longitude')

        # Process latitude and longitude (e.g., store in the database)
        # Implement your logic here

        return JsonResponse({'message': 'Geolocation received and processed successfully'})

    return JsonResponse({'error': 'Invalid request method'})



class Dashbord(TemplateView):
    template_name = 'dashboard.html'
    login_url = '/user_login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_details'] = UserProfile.objects.all()
        return context


class AboutPage(TemplateView):
    template_name = 'about.html'
    login_url = '/user_login'

class ContactPage(TemplateView):
    template_name = 'contact.html'
    login_url = '/user_login'

class TestimonialsPage(TemplateView):
    template_name = 'testimonials.html'
    login_url = '/user_login'

def terms_of_service(request):
    tos = TermsOfService.objects.latest('date_updated')
    return render(request, 'terms_of_service.html', {'tos': tos})

def accept_terms(request):
    form = AcceptTOSForm(request.POST or None)
    if form.is_valid():
        # Process user acceptance here (e.g., set a flag in user profile)
        return redirect('home')  # Redirect to home page or another view

    return render(request, 'accept_terms.html', {'form': form})


def job_count(request):
    ongoing_status_criteria = ['in_progress', 'processing', 'active']
    ongoing_jobs_count = UserProfile.objects.filter(status__in=ongoing_status_criteria).count()
    return render(request, 'job_count.html', {'ongoing_jobs_count': ongoing_jobs_count})

def account_status(request):
    user_profile = UserProfile.objects.get(user=request.user)
    return render(request, 'account_status.html', {'user_profile': user_profile})

class PrivacyPolicyPage(TemplateView):
    template_name = 'privacy_policy.html'
    login_url = '/user_login'

class FaqPage(TemplateView):
    template_name = 'faq.html'
    login_url = '/user_login'

class HowItWorksPage(TemplateView):
    template_name = 'functioning.html'
    login_url = '/user_login'


@login_required
def make_payment(request):
    if request.method == 'POST':
        # Process payment logic using Stripe or your chosen gateway
        # Handle payment form submission
        amount = 1000  # Amount in cents
        intent = stripe.PaymentIntent.create(
            amount=amount,
            currency='usd',
        )
        return render(request, 'payment_confirmation.html', {'client_secret': intent.client_secret})
    return render(request, 'payment.html')

def earnings_view(request):
    user_earnings = Earnings.objects.filter(user=request.user)
    return render(request, 'earnings.html', {'user_earnings': user_earnings})

def pending_payments_view(request):
    user_pending_payments = PendingPayments.objects.filter(user=request.user)
    return render(request, 'pending_payments.html', {'user_pending_payments': user_pending_payments})

def withdrawal_requests_view(request):
    pending_withdrawal_requests = WithdrawalRequest.objects.filter(user=request.user, is_approved=False)
    if request.method == 'POST':
        form = WithdrawalRequestForm(request.POST)
        if form.is_valid():
            withdrawal = form.save()
            return redirect('success_page')
    else:
        form = WithdrawalRequestForm()
    return render(request, 'withdrawal_requests.html', {'form': form})

def ongoing_projects_view(request):
    ongoing_projects = UserProfile.objects.all()
    return render(request, 'ongoing_projects.html', {'ongoing_projects': ongoing_projects})

users_accounts/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block contents %}


{% for user in user_details %}
<div class="header">
    <a href="{% url 'users_accounts:dashboard' %}"><img src="{% static './images/Jacom_logo2.png' %}" height="100px" width="120px"></a>
    <a href="{% url 'users_accounts:profile' %}" style="margin-left: 1100px; margin-top: 35px;" ><img src="{{user.profile_pictures.url}}" style="border-radius: 200px;" height="40px" width="40px"/></a>
</div>

<div class="row">
    <div class="col-3 col-s-3">
        <div class="aside-2">
            <h2>Dashboard</h2>

            <button onclick="getLocation()">Get Location</button>

            <div>
                <h2>Enter location</h2>

                <form>
                  <label for="location"></label>
                  <input type="geolocation" id="location" name="location" placeholder="Location">
                  <input type="submit" onclick="getLocation()" value="Submit">
                </form>
            </div>

            <div>
                <h2>
                    Account Settings
                </h2>
                <p>
                    Profile Information
                </p>
                
                    
                    <button><a href="{% url 'users_accounts:profile' %}">View Profile</a></button>
                    <p>
                        Account Security
                    </p>
                        Password Strength: [Strong/Weak]
                    <br>
                    <br>
                        Two-Factor Authentication: [Enabled/Disabled]
                    <br>
                    <br>
                        Last Login: [Date and time]
                    <br>
                    <br>
                    <button>[Change Password Button]</button>
            </div>

            <div>
                <h2>
                    Payment and Transactions
                </h2>
                <p>
                    Earnings and Payments
                </p>
                    Total Earnings: ${{ total_earnings }}
                    <br>
                    <br>
                    Pending Payments: {% for payment in user_pending_payments %} {{ payment.amount }} {% endfor %}
                    <br>
                    <br>
                    Withdrawal Requests: 
                    <form method="post" action="{% url 'users_accounts:withdrawals' %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <br>
                        <button type="submit">Cashout</button>
                    </form> {% for request in pending_withdrawal_requests %} {{ request.amount }} {% endfor %}
            </div>

            <div>
                <h2>
                    Help and Support
                </h2>
                        <a href="{% url 'users_accounts:faqpage' %}">FAQ:</a>
                    <br>
                    <br>
                        <a href="{% url 'users_accounts:contact' %}">Contact Support:</a>
                    <br>
                    <br>
                        <a href="{% url 'users_accounts:functioning' %}">User Guidelines:</a>
            </div>

            <div>
                <h2>
                    Get Featured
                </h2>
                        Boost Your Profile: Increase visibility by becoming a featured skilled worker.
                    <br>
                    <br>
                        Promote Your Project: Highlight your project for increased client attention.
                <a href="{% url 'users_accounts:about' %}">Learn More</a>
            </div>
        </div>
    </div>

    <div class="col-6 col-s-6 menu">
        <ul>
            <li>
                <h2>Welcome, {{request.user.username}}</h2>
                <p>{{user.work_bio}}</p>
                
                <div>
                    <div class="search">
                        <!-- <form id="searchForm">
                            <input type="text" id="searchInput" placeholder="Enter your search....">
                            <button onclick="performSearch()"><a href="{% url 'users_accounts:search' %}">Search</a></button>
                        </form> -->
                        <form action="{% url 'users_accounts:search' %}" method="GET">
                            <input type="text" name="q" placeholder="Search...">
                            <button type="submit">Search</button>
                        </form>
                          
                          
                    </div>
                </div>
            </li>

            <li>
                <div>
                    <h2>Quick Overview</h2>
                     <ul>
                        <br>
                        <li>Projects in Progress: {{ user.title }} - {{ user.ongoing_jobs_count }}</li>
                        <br>
                        <li>Unread Messages: [Number of unread messages]</li>
                        <br>
                        <li>Account Status: 
                            <p>
                                Verified: {% if user_profile.is_verified %}Yes{% else %}No{% endif %}
                            </p>
                            <p>
                                Active: {% if user_profile.is_active %}Yes{% else %}No{% endif %}
                            </p>
                        </li>
                    </ul>
                </div>
            </li>

            <li>
                <div>
                    <h2>
                        Ongoing Projects
                    </h2>
                    <ul>
                        <li>
                            Project Title: {{ user.title }}
                        </li>
                        <li>
                            Status: {{ user.status }}
                        </li>
                        <li>
                            Client: {{ user.client }}
                        </li>
                        <li>
                            Deadline: {{ user.deadline }}
                        </li>
                        <li>
                            Messages: <!-- Display number of messages -->
                        </li>
                    </ul>
                        <!-- <h3>
                            [Project Title 2]
                        </h3>
                    <ul>
                        <li>
                            Status: Waiting for Approval
                        </li>
                        <li>
                            Client: [Client's Name]
                        </li>
                        <li>
                            Deadline: [Project Deadline]
                        </li>
                        <li>
                            Messages: [Number of messages]
                        </li>
                    </ul>
                        <p>
                            Completed Projects
                        </p>
                        <h3>
                            [Project Title 3]
                        </h3>
                    <ul>
                        <li>
                            Status: Completed
                        </li>
                        <li>
                            Client: [Client's Name]
                        </li>
                        <li>
                            Feedback: [Rating and feedback]
                        </li>
                    </ul>
                </div>
            </li>
            <li>the food</li> -->
        </ul>
    </div>

    <div class="col-3 col-s-9">
        <div class="aside">
            <img src="{{user.profile_pictures.url}}" style="border-radius: 200px; width: 40px; height: 40px;"/>
            <ul>
                <li>
                    <h3>{{request.user.username}}</h3>
                </li>
                <li>
                    {{user.email}}
                </li>
            </ul>
            <button><a href="{% url 'users_accounts:update' pk=user.id %}">Edit Profile</a></button>
        </div>
    </div>

    <div class="col-3 col-s-12">
        <div class="aside-3">
            <div>
                <h2>
                    Messages
                </h2>
                <p>
                    Recent Messages
                </p>
                        [Client's Name]: "Discussing project details."
                    <br>
                    <br>
                        [Skilled Worker's Name]: "Project update and timeline."
                    <br>
                    <br>
                        [Admin]: "Important platform announcement."
                    <br>
                    <br>
                <button>[View All Messages Button]</button>
            </div>

            <div>
                <h2>
                    Notifications
                </h2>
                <h3>
                    [Number] New Notifications
                </h3>
                        [Notification 1]
                    <br>
                    <br>
                        [Notification 2]
                    <br>
                    <br>
                        [Notification 3]
                    <br>
                    <br>
                <button>[View All Notifications Button]</button>
            </div>
            <h2>Report Problem</h2>
            <p>
                <form>
                    <label>
                        <input type="email" placeholder="Email....">
                    </label>
                    <label>
                        <input type="number" placeholder="Number....">
                    </label>
                    <label>
                        <input type="text" placeholder="Report Your Problem....">
                    </label>
                </form>
            </p>
        </div>
    </div>
    
</div>

        <div>
            <a href="{% url 'users_accounts:logout' %}">Log Out</a>
        </div>
{% endfor %}

{% endblock %}

users_accounts/templates/footer.html
{% extends 'base.html' %}
{% load static %}


{% block contents %}

<footer class="site-footer">
    <div class="container">
        <div class="footer-content">
            <h4>Connecting Skilled Workers with Clients, Seamlessly.</h4>
            <p>At Jacom, we specialize in matching skilled professionals with clients to ensure exceptional project outcomes.</p>

            <div class="contact-info">
                <h5>Contact Us</h5>
                <ul>
                    <li>Email: teamjacom@gmail.com</li>
                    <li>Phone: +234-7068-90-5564</li>
                </ul>
            </div>

            <div class="social-icons">
                <!-- Add your social media icons/links here -->
                <!-- Example: -->
                <a href="#" class="social-icon">Facebook</a>
                <a href="#" class="social-icon">Twitter</a>
                <a href="#" class="social-icon">LinkedIn</a>
            </div>

            <div class="Copyright-info">
                <p>Copyright © 2023 Jacom. All rights reserved.</p>
            </div>
        </div>
        
    </div>
</footer>

{% endblock %}

users_accounts/templates/password_reset_complete.html
{% extends "base.html" %}

{% block contents %}

<div>
    <h3>Password Reset Complete</h3>
    <button>
        <a href="{% url 'users_accounts:login' %}">Log in</a>
    </button>
</div>

{% endblock %}

users_accounts/templates/password_reset_done.html
<h3>Password Reset Sent</h3>

users_accounts/templates/sign_up.html
{% extends 'base.html' %}
{% load static %}


{% block contents %}

<div class="homeicon_login">
    <a href="{% url 'users_accounts:homepage' %}"><img src="{% static './images/Jacom_logo2.png' %}" height="100px" width="120px"></a>
</div>

<div class="container">

    <div class="column">
        <h1>Sign Up for Free</h1>
       <div class="signup_form">
            <div class="create_your_account">
                <h2>
                    Create Your Account
                </h2>
            </div>
        
            <div class="jacom_signup_form">
                <form method="post">
                    {% csrf_token %}
                    <!-- {{ form.as_p }} -->
                    <label for="">Username:
                        <input type="text" name="username" placeholder="Username" required />
                    </label>
                    <br>
                    <label for="">Email:
                        <input type="email" name="email" placeholder="Email" required>
                    </label>
                    <br>
                    <label for="">Password:
                        <input type="password" name="password" placeholder="Password" required />
                    </label>
                    <p>
                        By clicking Accept, you agree to our <br> <a href="{% url 'users_accounts:terms_of_service' %}">Terms of Service</a> and <a href="{% url 'users_accounts:privacy&policy' %}">Privacy Policy</a>
                        <br><input type="checkbox" id="checkButton" onclick="checkButtonClick()">
                        <label for="checkButton">Accept</label>
                    </p>
                    
                    <button type="submit">Sign Up</button>
                </form>
                <div class="have_an_account">
                    <p>Have an Account?</p>
                    <p>Log In<a href="{% url 'users_accounts:login' %}"> Here</a> </p>
                </div>
            </div>
       </div>
    </div>
    
    <div class="column_two">
        <h1>Join JACOM and Unlock a World of Opportunities</h1>
        <!-- 
        <div>
            <div>
                <img src="{% static './images/jacom_young_tailor.webp' %}">
                <img src="{% static './images/jacom_happy_colleagues.webp' %}">
            </div>
        </div> -->

        <div class="slider-container">
            <div class="slider">
                <div class="slide">
                    <p>
                        Welcome to JACOM, where skills meet success! Sign up now to connect with
                        <br>skilled workers or find clients for your expertise. It's quick, easy, and absolutely free.
                    </p>
                </div>
        
                <div class="slide">
                    <p>Why Join JACOM ?</p>
                    Access a Diverse Talent Pool: Whether you're a client looking for skilled workers or a
                    professional showcasing your 
                </div>

                <div class="slide">
                    talents, our platform offers a wide range of expertise to
                    choose from.
                </div>

                <div class="slide">
                    Streamlined Hiring Process: Find the perfect match for your project without the hassle. Our
                    user-friendly interface makes the hiring process simple and efficient.
                </div>
                    
                <div class="slide">
                    Verified Professionals: Rest assured that all skilled workers on our platform are vetted and
                    verified, ensuring high-quality work and reliable service.
                </div>
                    
                <div class="slide">
                    Secure Transactions: Your security is our priority. We offer secure payment gateways for
                    seamless transactions between clients and skilled workers.
                </div>
                    
                
        
                <div class="slide">
                    <p>What Happens Next?</p>
                    <p>Once you sign up, you can:</p>
                </div>

                <div class="slide">
                    Create Your Profile: Build a compelling profile showcasing your skills, experience, and
                    certifications. Make a strong first impression on potential clients or skilled workers.
                </div>
                
                <div class="slide">
                    Browse Listings: Clients can explore skilled worker profiles and portfolios, while
                    professionals can view available projects posted by clients.
                </div>
                        
                <div class="slide">
                    Start Connecting: Message potential collaborators, discuss project details, negotiate
                    terms, and get to work!
                </div>
                        
        
                <!-- <div>
                    <div>
                        <img src="{% static './images/jacom_sharing_ideas_women.webp' %}">
                        <img src="{% static './images/jacom_smile_lady.webp' %}">
                    </div>
                </div> -->
        
                <div class="slide">
                    <p>Questions? We're Here to Help!</p>
                    <p>If you have any questions or need assistance, our support team is ready to assist you.
                        <br>Contact Support <a href="{% url 'users_accounts:contact' %}">Contact Us</a>
                    </p>
                </div>
            </div>
            <div class="slide_button">
                <button class="prev" onclick="moveSlide(-1)">Previous</button>
                <button class="next" onclick="moveSlide(1)">Next</button>
            </div>
        </div>
        
    </div>
</div>
{% endblock %}